"""empty message

Revision ID: 13712f2a06bc
Revises: cd7f88f107bc
Create Date: 2025-03-26 17:31:45.612574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13712f2a06bc'
down_revision = 'cd7f88f107bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.alter_column('personajes_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('planetas_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.alter_column('planetas_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('personajes_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
